# Generated by Django 5.0 on 2024-04-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_paid',
            field=models.FloatField(default=0),
        ),
    ]
