# Generated by Django 5.0 on 2023-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='length',
            field=models.IntegerField(),
        ),
    ]
