# Generated by Django 5.0 on 2024-01-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_booking_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
