# Generated by Django 5.0 on 2024-01-23 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_end_date_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 23, 23, 21, 9, 113687)),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 23, 23, 21, 9, 113669)),
        ),
    ]
